Update to DisplayLink v5.6.0 Offical Release
displaylink-rpm/displaylink-rpm pull request #207
Opened 2022-05-21 21:43 UTC by GrzegorzBB

2022-05-22 05:14 UTC, elguero requested changes
Thank you for the contribution.

2022-05-22 05:14 UTC, elguero commented on Makefile
> +RELEASE        := 2
This should be '1' since this is the first release with this driver version.

2022-05-22 05:14 UTC, elguero commented on displaylink.spec
> +%{!?_release:%global _release 2}
Release '1'

2022-05-22 20:34 UTC, GrzegorzBB commented
Thanks for the tips!

2022-05-28 23:03 UTC, GrzegorzBB reviewed
Version changed, I hope now it is everything.

2022-06-02 05:21 UTC, ParadoxGuitarist commented
Just wanted to say I built this on Fedora 36 after modifying the Makefile to remove the i386 stuff and seems like it's working well!

2022-06-02 11:04 UTC, dominikzogg commented
did it as @ParadoxGuitarist explained, works

2022-06-05 15:24 UTC, merged

2022-06-05 15:24 UTC, elguero commented
Thank you for your contribution!